spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pftdb
    username: pftdb
    password: pftdb

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true